export interface FirebaseConst {
  LOCAL_STORAGE_TOKEN_NAME: string;
  LOCAL_STORAGE_REFRESH_TOKEN_NAME: string;
  LOCAL_STORAGE_EXPIRES_TOKEN_NAME: string;
  LOCAL_STORAGE_USER_EMAIL_NAME: string;
  LOCAL_STORAGE_USER_DISPLAY_NAME: string;
  REFRESH_TOKEN_GRANT_TYPE_NAME: string;
}
